### PR TITLE
Updated readme - Rough draft

### PR DESCRIPTION
**Pull request by Noah-Davy**
feel free to add/remove, there's definitely more content to be added, just my initial ideas.

### CODE REVIEW

**Comment by Morganplant** [comment]
New readme looks good the only thing I can think of to make the install easier for a user is that instead of getting them to install modules themself we can just get the to run 
`pip install -r requirements.txt`

**Review by Morganplant — APPROVED** [review]

**Review by Morganplant — CHANGES_REQUESTED** [review]
New readme looks good the only thing I can think of to make the install easier for a user is that instead of getting them to install modules themself we can just get the to run 
`pip install -r requirements.txt`

**Comment by Noah-Davy** [comment]
should be all updated, good to go now

**Review by Morganplant — APPROVED** [review]
LGTM

**Comment by EddieJ01** [comment]
also think we need `pip install rembg`  in the utils.py

**Pull request merged**
